import { describe, expect, it } from 'vitest';
import { createProceduralVisual, makeVisualCacheKey, normalizeGeneratedImage } from './visualAssets';

describe('visual assets', () => {
  it('creates a stable cache key from prompt, seed, and reference', async () => {
    const first = await makeVisualCacheKey({ prompt: 'macro glass', seed: 'abc', referenceHash: '123' });
    const second = await makeVisualCacheKey({ prompt: 'macro glass', seed: 'abc', referenceHash: '123' });
    expect(first).toBe(second);
  });

  it('normalizes generated bytes through the injected codec', async () => {
    const asset = await normalizeGeneratedImage(
      { mimeType: 'image/png', data: 'aGVsbG8=' },
      { compress: async () => ({ dataUrl: 'data:image/webp;base64,aGVsbG8=', byteLength: 5 }) },
      'key',
      'Hero'
    );
    expect(asset.source).toBe('generated');
    expect(asset.mimeType).toBe('image/webp');
  });

  it('creates an offline SVG fallback without remote URLs', () => {
    const asset = createProceduralVisual({ seed: 'abc123', accent: '#22C55E', background: '#0A0A0A', alt: 'Textura técnica' });
    expect(asset.source).toBe('procedural');
    expect(asset.dataUrl).toMatch(/^data:image\/svg\+xml/);
    expect(decodeURIComponent(asset.dataUrl)).not.toContain('https://');
  });
});
