import React, { useMemo, useState } from 'react';

interface Props { projects: any[]; onDeleteProject: (id: string) => void; onSelectProjectForStudio: (project: any) => void }
export const LandingBank: React.FC<Props> = ({ projects, onDeleteProject, onSelectProjectForStudio }) => {
  const [selectedId, setSelectedId] = useState(projects[0]?.id);
  const selected = useMemo(() => projects.find(item => item.id === selectedId) || projects[0], [projects, selectedId]);
  if (!projects.length) return <section className="bg-[#141414] p-16 text-center"><h1 className="text-xl">Banco de Landing Pages vacío</h1><p className="mt-3 text-sm text-[#A1A1A1]">Las piezas que superen 8.5 aparecerán aquí.</p></section>;
  return <section className="flex flex-col gap-6"><div><p className="mono text-[11px] uppercase tracking-widest text-[#737373]">BANCO CURADO</p><h1 className="text-3xl font-semibold">Landing pages y prompts de origen</h1></div><div className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><div className="flex flex-col gap-2">{projects.map(item => <button key={item.id} type="button" onClick={() => setSelectedId(item.id)} className={`text-left p-5 ${item.id === selected?.id ? 'bg-[#282828]' : 'bg-[#141414]'}`}><div className="flex justify-between gap-3"><span className="text-sm font-medium">{item.blueprint?.metadata?.title || item.title || 'Landing heredada'}</span><span className="mono text-xs text-[#22C55E]">{item.audit?.scores?.average || '—'}</span></div><p className="mt-2 line-clamp-2 text-xs text-[#A1A1A1]">{item.request?.brief?.valueProposition || item.valueProp || 'Registro conservado'}</p></button>)}</div>{selected && <div className="grid gap-4 lg:grid-cols-2"><div className="min-h-[620px] bg-[#141414] p-4"><iframe title="Saved Landing Preview" sandbox="allow-scripts" srcDoc={selected.htmlCode} className="h-full min-h-[580px] w-full bg-[#0A0A0A]" /></div><div className="bg-[#141414] p-5 flex flex-col gap-4"><div className="flex flex-wrap justify-between gap-3"><button type="button" onClick={() => onSelectProjectForStudio(selected)} className="bg-[#F3F3F3] px-4 py-2 text-xs font-semibold text-[#0A0A0A]">Abrir en Studio</button><button type="button" onClick={() => onDeleteProject(selected.id)} className="text-xs text-[#E06D53]">Eliminar</button></div><label className="flex flex-col gap-2 text-xs text-[#737373]">Prompt de origen<textarea aria-label="Prompt de origen" readOnly value={selected.request?.executedPrompt || selected.prompts?.masterPrompt || ''} rows={16} className="bg-[#0A0A0A] p-3 font-mono text-xs text-[#A1A1A1]" /></label><div className="text-xs text-[#A1A1A1]">Semilla: {selected.request?.ssotSeed || selected.ssotVector?.seed || 'heredada'}</div></div></div>}</div></section>;
};
